/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as DetailsIdRouteImport } from './routes/details.$id'

const WatchlistLazyRouteImport = createFileRoute('/watchlist')()
const RecentLazyRouteImport = createFileRoute('/recent')()
const CategoryLazyRouteImport = createFileRoute('/category')()
const IndexLazyRouteImport = createFileRoute('/')()

const WatchlistLazyRoute = WatchlistLazyRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/watchlist.lazy').then((d) => d.Route))
const RecentLazyRoute = RecentLazyRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recent.lazy').then((d) => d.Route))
const CategoryLazyRoute = CategoryLazyRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/category.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/play.$id.lazy').then((d) => d.Route))
const DetailsIdRoute = DetailsIdRouteImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/details.$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/category': typeof CategoryLazyRoute
  '/recent': typeof RecentLazyRoute
  '/watchlist': typeof WatchlistLazyRoute
  '/details/$id': typeof DetailsIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/category': typeof CategoryLazyRoute
  '/recent': typeof RecentLazyRoute
  '/watchlist': typeof WatchlistLazyRoute
  '/details/$id': typeof DetailsIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/category': typeof CategoryLazyRoute
  '/recent': typeof RecentLazyRoute
  '/watchlist': typeof WatchlistLazyRoute
  '/details/$id': typeof DetailsIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category'
    | '/recent'
    | '/watchlist'
    | '/details/$id'
    | '/play/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category'
    | '/recent'
    | '/watchlist'
    | '/details/$id'
    | '/play/$id'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/recent'
    | '/watchlist'
    | '/details/$id'
    | '/play/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryLazyRoute: typeof CategoryLazyRoute
  RecentLazyRoute: typeof RecentLazyRoute
  WatchlistLazyRoute: typeof WatchlistLazyRoute
  DetailsIdRoute: typeof DetailsIdRoute
  PlayIdRoute: typeof PlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$id': {
      id: '/details/$id'
      path: '/details/$id'
      fullPath: '/details/$id'
      preLoaderRoute: typeof DetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryLazyRoute: CategoryLazyRoute,
  RecentLazyRoute: RecentLazyRoute,
  WatchlistLazyRoute: WatchlistLazyRoute,
  DetailsIdRoute: DetailsIdRoute,
  PlayIdRoute: PlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
